### ISSUE TITLE
Cell traffic empty in Xperia X Sailfish build

### ISSUE THREAD

**Issue by niemisenjussi** [custodian/harbour-systemmonitor#16]
Xperia X Sailfish build cell -traffic is empty because of changed paths. rmnet devices has been changed from /sys/class/net/ to /sys/devices/virtual/net/.

Here is addition for Xperia which works:
```
@@ -8,6 +8,8 @@ DataSourceCell::DataSourceCell(SystemSnapshot *parent) :
     for (int i=0;i<=7;i++) {
         m_sourcesRx.append(registerSystemSource(QString("/sys/class/net/rmnet%1/statistics/rx_bytes").arg(i)));
         m_sourcesTx.append(registerSystemSource(QString("/sys/class/net/rmnet%1/statistics/tx_bytes").arg(i)));
+        m_sourcesRx.append(registerSystemSource(QString("/sys/devices/virtual/net/rmnet_data%1/statistics/rx_bytes").arg(i)));
+        m_sourcesTx.append(registerSystemSource(QString("/sys/devices/virtual/net/rmnet_data%1/statistics/tx_bytes").arg(i)));
     }
```

[nemo@Sailfish ~]$ cd /sys/class/net/
[nemo@Sailfish net]$ ls
lo	     rmnet_data1  rmnet_data3  rmnet_data5  rmnet_data7  sit0
rmnet_data0  rmnet_data2  rmnet_data4  rmnet_data6  rmnet_ipa0	 wlan0
[nemo@Sailfish net]$ ll
total 0
lrwxrwxrwx 1 root root 0 Oct 18 11:15 lo -> ../../devices/virtual/net/lo
lrwxrwxrwx 1 root root 0 Oct 18 11:15 rmnet_data0 -> ../../devices/virtual/net/rmnet_data0
lrwxrwxrwx 1 root root 0 Oct 18 11:15 rmnet_data1 -> ../../devices/virtual/net/rmnet_data1
lrwxrwxrwx 1 root root 0 Oct 18 11:15 rmnet_data2 -> ../../devices/virtual/net/rmnet_data2
lrwxrwxrwx 1 root root 0 Oct 18 11:15 rmnet_data3 -> ../../devices/virtual/net/rmnet_data3
lrwxrwxrwx 1 root root 0 Oct 18 11:15 rmnet_data4 -> ../../devices/virtual/net/rmnet_data4
lrwxrwxrwx 1 root root 0 Oct 18 11:15 rmnet_data5 -> ../../devices/virtual/net/rmnet_data5
lrwxrwxrwx 1 root root 0 Oct 18 11:15 rmnet_data6 -> ../../devices/virtual/net/rmnet_data6
lrwxrwxrwx 1 root root 0 Oct 18 11:15 rmnet_data7 -> ../../devices/virtual/net/rmnet_data7
lrwxrwxrwx 1 root root 0 Oct 18 11:15 rmnet_ipa0 -> ../../devices/virtual/net/rmnet_ipa0
lrwxrwxrwx 1 root root 0 Oct 18 11:15 sit0 -> ../../devices/virtual/net/sit0
lrwxrwxrwx 1 root root 0 Oct 18 11:15 wlan0 -> ../../devices/soc.0/7a24900.sdhci/mmc_host/mmc2/mmc2:0001/mmc2:0001:2/net/wlan0

**Comment by custodian** [comment]
Paths are same.
Naming conversion of rmnet devices has been changed from "rmnet?" to "rmnet_data?".

Proper approarch is to use filters:
https://github.com/custodian/harbour-systemmonitor/pull/14/commits/2641e4a0c24340cea43b7d99a5c5eae7df48938b
