### ISSUE TITLE
harbour-systemmonitord seems to be leaking memory

### ISSUE THREAD

**Issue by monich** [custodian/harbour-systemmonitor#8]
![1001_heap_changes_2](https://cloud.githubusercontent.com/assets/5909522/5602717/1a63ef60-9372-11e4-8c9c-8a12fa763ec2.png)

**Comment by custodian** [comment]
What application have you used to monitor memory usage?
Daemon does not directly allocated any unsafe memory that can be leaked. This is either non-proper qobject live cycle, or sql db related cache.

**Comment by monich** [comment]
This is a part of the endurance report generated by crash reporter:

https://github.com/mer-qa/crash-reporter

The process memory usage snapshots are taken from /proc fs, I believe. In any case, this information is coming more or less directly from the kernel, you can trust the numbers. I suggest you to profile your daemon with valgrind. Directly or indirectly, it is leaking memory.

**Comment by monich** [comment]
Memory usage grows in the sqlite code. It's easy enough to notice by running your systemmonitord under valgrind --tool=massif. Nothing points to any leaks in your code. So I guess it's not directly your fault but there might be some sort of workaround for it.

**Comment by monich** [comment]
That's sqlite cache. The default size is 2MB. Once it reaches 2MB is stops growing. If you don't need that much cache (and you probably don't) please consider reducing it using the PRAGMA cache_size statement:

http://www.sqlite.org/pragma.html#pragma_cache_size

Not really an issue. Closing.

**Comment by monich** [comment]
Better yet, you don't have to do anything at all. In update13 the default sqlite cache size will be reduced from 2MB to 500KB for all processes including yours.
